### ISSUE TITLE
Problem with dates

### ISSUE THREAD

**Issue by maxsh8x** [e-oj/Fawn#37]
```js
...
.save('collection', new Entity({
   date: new Date('2017-10-10')
}))
.run({ useMongoose: true })
```

Date saved as string

**Comment by e-oj** [comment]
That's because the objects are converted to JSON strings before being saved as a way to deal with the [special characters "."  and "$" in object keys](https://github.com/e-oj/Fawn/issues/8). This had unintended consequences for objects like ObjectID and Date because they get converted to strings. I'll push a fix to address this in the next couple of days.

**Comment by e-oj** [comment]
related to #34

**Comment by e-oj** [comment]
Upgrade your version of Fawn and it should work fine. Let me know if the issue persists
