### ISSUE TITLE
Consider removing all direct references to require("mongoose") in the code

### ISSUE THREAD

**Issue by jake-billings** [e-oj/Fawn#48]
See Issue #46 

I have a PR pending for removing require("mongoose") from gen utils.

I suggest removing the reference to require("mongoose") lib/fawn.js. It makes it unclear when loading mongoose results in a duplicate package in which no registered models will be available to users of Fawn transactions.

A warn() message might work too, but I suggest removing the require call altogether. This forces all references to mongoose from within Fawn to point at the correct instance, which is shared with the user of the library.

**Comment by e-oj** [comment]
Thanks for the PR. Mongoose still needs to be required directly in fawn.js; it handles the case where a user does not provide an instance of mongoose or would rather use the native driver.

**Comment by jake-billings** [comment]
I'm suggesting that Fawn not support the case where a user does not provide an instance of mongoose. If Fawn supports this, it is easy to accidentally create a case where Fawn accesses a different instance of the mongoose library from the one that a user of the Fawn library is using.

For example, I install Mongoose 4.11.8 and Fawn installs 4.11.3. Node gives two separate copies to me and Fawn

**Comment by e-oj** [comment]
The thing is, a user might not use mongoose in their project at all (#10) and that should be supported. Also, the native driver is much faster than mongoose so that option should be available. There's really no confusion here; Look at the code:
```javascript
    if (dbType === "object") {
      if (isMongoose(db)) {
        mongoose = db;
      }
      else{
        throw new Error("The provided mongoose instance is invalid");
      }
    }
    else{
      mongoose = require("mongoose");
      options.useMongoClient = true;
      mongoose.connect(db, options);
    }
```
If the user provides an instance of mongoose, we use that. Else, we use our version of mongoose.

**Comment by jake-billings** [comment]
What about forcing a user to explicitly set a flag if they don't pass Fawn an instance of mongoose?

I could see an instance where a user forgets to pass his or her mongoose instance to Fawn.

**Comment by e-oj** [comment]
Well, to use Fawn, you must call Fawn.init which requires at least a connection String or a mongoose instance. If the user forgets to call Fawn.init, an error will be thrown. As a result, a user can't really forget to initialize Fawn. What could happen is, a user might accidentally pass a connection string instead of a mongoose instance but that's what the docs are for. Forcing users to set a flag adds an extra step to the process that non-mongoose users might find unnecessary

**Comment by jake-billings** [comment]
Fair enough. I'm fine closing the issue.

**Comment by e-oj** [comment]
Cool. I've published your pr. Upgrade to 2.1.3 and it should be fine

**Comment by e-oj** [comment]
Sorry, I meant version 2.1.4

**Comment by jaimin275** [comment]
I have resolved this error by changing "obj.modelSchemas" to "obj.Schema" in isMongoose(db) function. I'm using version 2.1.5
